version: '3'
services:
  postgres:
    image: "crunchydata/crunchy-postgres:centos7-10.5-2.1.0"
    env_file: pg.env
    networks:
      - pgnetwork
    ports:
      - "5432:5432"
    volumes:
      - pgvolume:/pgdata
  pgadmin4:
    image: "crunchydata/crunchy-pgadmin4:centos7-10.5-2.1.0"
    env_file: pgadmin.env
    networks:
       - pgnetwork
    ports:
      - "5050:5050"
    volumes:
      - pg4volume:/var/lib/pgadmin
      - ./backups:/var/lib/pgadmin/storage
    depends_on:
      - postgres

networks:
  pgnetwork:

volumes:
  pgvolume:
  pg4volume:
